server:
  port: 21900
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
      #cluster-name: cdi-es
      #cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
